services:
  django:
    build:
      context: .
    container_name: django_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             daphne -b 0.0.0.0 -p 8000 taskmainder.asgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    restart: unless-stopped

  redis:
    image: redis:6.2
    container_name: redis
    restart: unless-stopped

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  celery_worker:
    build:
      context: .
    container_name: celery_worker
    command: celery -A taskmainder worker --loglevel=info
    depends_on:
      - redis
      - django
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

  celery_beat:
    build:
      context: .
    container_name: celery_beat
    command: celery -A taskmainder beat --loglevel=info
    depends_on:
      - redis
      - django
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  static_volume:
  postgres_data: